const data = {
  products: [
    {
      _id: '1',
      name: 'Nike Slim Shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },

    {
      _id: '2',
      name: 'adidas Slim Shirt',
      slug: 'adidas-slim-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 130,
      countInStock: 8,
      brand: 'Adidas',
      rating: 4.4,
      numReviews: 15,
      description: 'branded shirt',
    },
    {
      _id: '3',
      name: 'Nike Slim pant',
      slug: 'adidas-slim-pant',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 110,
      countInStock: 5,
      brand: 'Nike',
      rating: 4.0,
      numReviews: 12,
      description: 'high quality pants',
    },
    {
      _id: '4',
      name: 'Adidas Fit pant',
      slug: 'adidas-fit-pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 115,
      countInStock: 0,
      brand: 'adidas',
      rating: 4.3,
      numReviews: 14,
      description: 'high quality fit pants',
    },
  ],
};
 export default data;